---
BrokenFiles:
  - /usr/bin/nl-tctree-list
  - /usr/bin/ssh-add
  - /usr/sbin/tc
  - /usr/bin/rpmdb
  - /usr/sbin/blkmapd
  - /usr/bin/dnf-3
  - /usr/bin/python3
  - /usr/sbin/ss
  - /usr/bin/systemd-dissect
  - /usr/bin/newuidmap
  - /usr/sbin/xfs_mdrestore
  - /usr/bin/ld.so
  - /usr/bin/ima-add-sigs
  - /usr/sbin/xfs_bmap
  - /usr/bin/aulastlog
  - /usr/bin/nl-addr-add
  - /usr/bin/gpgparsemail
  - /boot/initramfs-5.14.0-570.12.1.el9_6.x86_64.img
  - /sbin/anacron
  - /usr/sbin/dumpe2fs
  - /usr/bin/systemd-inhibit
  - /usr/sbin/nstat
  - /bin/seq
  - /bin/unexpand
  - /bin/rmdir
  - /usr/bin/setleds
  - /usr/bin/pkill
  - /bin/systemd-sysext
  - /usr/bin/hexdump
  - /bin/taskset
  - /usr/bin/rsync
  - /usr/bin/ssh-keyscan
  - /sbin/blkdiscard
  - /usr/bin/ndptool
  - /sbin/filefrag
  - /usr/bin/sg_xcopy
  - /boot/vmlinuz-5.14.0-570.12.1.el9_6.x86_64
  - /usr/bin/sleep
  - /bin/mkfifo
  - /bin/sg_stream_ctl
  - /usr/bin/nproc
  - /usr/bin/base64
  - /usr/bin/cpio
  - /usr/bin/chcon
  - /bin/rpm2archive
  - /usr/bin/choom
  - /bin/sg_scan
  - /usr/bin/journalctl
  - /usr/bin/chmem
  - /sbin/load_policy
  - /usr/bin/nmtui
  - /sbin/bridge
corruptedBootFiles:
  - /usr/bin/ssh-add
  - /usr/bin/sg_wr_mode
  - /usr/sbin/mkdosfs
  - /usr/sbin/swapon
  - /usr/bin/systemd-firstboot
  - /usr/sbin/runlevel
  - /usr/bin/nf-exp-add
  - /usr/sbin/mke2fs
  - /usr/sbin/e2label
  - /usr/bin/xmlwf
  - /usr/sbin/update-alternatives
  - /usr/bin/expand
  - /usr/bin/nl-class-add
  - /usr/bin/team2bond
  - /usr/bin/soelim
  - /usr/sbin/create-cracklib-dict
  - /usr/bin/sg_copy_results
  - /usr/sbin/xfs_mkfile
  - /usr/sbin/wipefs
  - /usr/bin/chcon
  - /usr/bin/sg_rdac
  - /usr/bin/gpgtar
  - /usr/bin/cat
  - /usr/bin/killall
  - /usr/bin/getfattr
  - /usr/sbin/irqbalance
  - /usr/sbin/applygnupgdefaults
  - /usr/bin/mktemp
  - /usr/bin/xb-tool
  - /usr/bin/ionice
  - /usr/bin/sudoedit
  - /usr/sbin/mkhomedir_helper
  - /usr/sbin/partx
  - /usr/bin/xgettext
  - /usr/bin/mount
  - /usr/bin/os-prober
  - /usr/bin/csplit
  - /usr/bin/gzexe
  - /usr/sbin/ctstat
  - /usr/sbin/ldattach
  - /usr/bin/showconsolefont
  - /usr/bin/bootctl
  - /usr/bin/passwd
  - /usr/bin/rpm2cpio
  - /usr/bin/dbxtool
  - /usr/sbin/unix_update
  - /usr/bin/grub2-mklayout
  - /usr/sbin/chcpu
  - /usr/sbin/fsck.ext2
  - /usr/sbin/alternatives
  - /usr/bin/link
  - /usr/bin/base32
  - /usr/bin/tload
  - /usr/sbin/pwunconv
  - /usr/sbin/getpidprevcon
  - /usr/sbin/virt-what
  - /usr/bin/udevadm
  - /usr/sbin/blkzone
  - /usr/bin/chown
  - /usr/bin/systemd-detect-virt
  - /usr/sbin/modprobe
  - /usr/sbin/sfdisk
  - /usr/bin/kbdrate
  - /usr/sbin/mkfs.cramfs
  - /usr/bin/command
  - /usr/bin/gtroff
  - /usr/bin/tar
  - /usr/bin/msgfmt
  - /usr/bin/psfaddtable
  - /usr/bin/post-grohtml
  - /usr/bin/sginfo
  - /usr/sbin/rdma
  - /usr/bin/man
  - /usr/bin/zfgrep
  - /usr/sbin/exportfs
  - /usr/sbin/mkfs.xfs
  - /usr/bin/sg_write_long
  - /usr/bin/gpg-error
  - /usr/bin/lslogins
  - /usr/bin/grub2-mkrelpath
  - /usr/bin/readelf
  - /usr/bin/apropos.man-db
  - /usr/sbin/newusers
  - /usr/bin/fwupdmgr
  - /usr/sbin/validatetrans
  - /usr/sbin/intel_sdsi
  - /usr/bin/hexdump
  - /usr/sbin/kpartx
  - /usr/bin/sg_get_config
  - /usr/bin/yum
